Made a really clean way of loading images that will be reusable
RickLeinecker/Fortuna pull request #113
Opened 2020-02-29 03:20 UTC by SecondThread

**Description**
Created a clean way of loading images in a way that is reusable that easily seperates from the UI where the images are used.

**Type of change**
Check options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Fix or feature that would cause existing functionality to not work as expected
- [ ] This change requires a update in the design document

**Steps to Verify Functionality**
Passes flow and loads images like it should

**Final Checklist:**
Go down the list and check them off.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the design document (if applicable)
- [x] My changes generate no new warnings
- [x] Pulled updated master branch (if changed since branch creation) and corrected any conflicts, if any occur.

2020-02-29 14:55 UTC, blaiadam commented on src/battlearena/BattleArena.js
> +							<button type="button" className="btn">Training Arena</button>
White space too long.

2020-02-29 14:55 UTC, blaiadam commented on src/battlearena/BattleArena.js
> +							<option defaultValue>Select a Tank</option>
Same as previous comment.

2020-02-29 14:56 UTC, blaiadam commented on src/battlearena/BattleArena.js
> +						leaderNames={ ["We", "Need", "To", "Get", "These", "With", "An", "API", "Call", "Still"] }
Lmao

2020-02-29 15:01 UTC, blaiadam commented on src/trainingarena/TrainingArena.js
> +										<Link to="Battleground">
White space issue.

2020-02-29 15:14 UTC, blaiadam requested changes
Looks great! Didn't pass flow however, I'll attach the errors.

![Screenshot (29)](https://user-images.githubusercontent.com/42626045/75610082-26e3f500-5adc-11ea-985a-f0e4de1d885b.png)

![Screenshot (28)](https://user-images.githubusercontent.com/42626045/75610087-306d5d00-5adc-11ea-9cc1-adc34aa93035.png)

2020-03-01 01:53 UTC, SecondThread commented
Yikes, thanks for catching!

2020-03-01 05:16 UTC, blaiadam approved these changes
Looks good on my end.

2020-03-01 18:21 UTC, merged