Create new tank armory
RickLeinecker/Fortuna pull request #155
Opened 2020-03-12 20:32 UTC by JorgeVidal29

This creates a new tank for the user from the armory

**Description**
Creates a new tank for the user functionality added to armory

Resolves #(replace parentheses and the stuff here with the issue number, if there isn't one, create one.) 

**Type of change**
Check options that are relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Fix or feature that would cause existing functionality to not work as expected
- [ ] This change requires a update in the design document

**Steps to Verify Functionality**
Make a bulleted/numbered list of steps to verify this feature/bugfix. Include screenshots if necessary.

**Final Checklist:**
Go down the list and check them off.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the design document (if applicable)
- [x] My changes generate no new warnings
- [x] Pulled updated master branch (if changed since branch creation) and corrected any conflicts, if any occur.

2020-03-12 21:07 UTC, SecondThread requested changes
Doesn't pass flow. Also the cancel button doesn't close the dialog. Also if you click outside the dialog you can't open it a second time. (All three of those are caused by the same thing, but I won't spoil that because I think it is a good learning experience and shows why flow is so helpful)

2020-03-12 21:07 UTC, SecondThread commented on src/armory/Armory.js
> -		console.log(body);
thanks :)

2020-03-12 21:07 UTC, SecondThread commented on src/armory/Armory.js
>  		const body = await response.text();
change to response.json() please

2020-03-12 21:07 UTC, SecondThread commented on src/armory/Armory.js
> +						<select className="dropdownMenu" value={this.state.selectedTankId} onChange={this.handleChangeInTankOptions}>{tankOptions.map(({ value, label }, index) => <option key={index}  value={value}>{la
This is a really long line

2020-03-12 21:07 UTC, SecondThread commented on src/armory/CreateNewTankPopup.js
> +            newTankDialogOpen: false,
fix whitespace please

2020-03-12 21:34 UTC, JorgeVidal29 commented on src/armory/Armory.js
> +						<select className="dropdownMenu" value={this.state.selectedTankId} onChange={this.handleChangeInTankOptions}>{tankOptions.map(({ value, label }, index) => <option key={index}  value={value}>{la
https://stackblitz.com/edit/react-select-example this is where I got that idea

2020-03-13 01:01 UTC, SecondThread approved these changes
Make sure to fix PR comments before pushing

2020-03-13 01:01 UTC, SecondThread commented on src/armory/Armory.js
> +	//The || in the values are for a warning read more here https://github.com/mui-org/material-ui/issues/4904
If you read the issue linked it says that this issue isn't actually a problem with Material Design. But also you shouldn't be passing null in there anyway...

2020-03-13 01:01 UTC, SecondThread commented on src/armory/CreateNewTankPopup.js
> +    handleCreateClick(): void {
please fix spacing

2020-03-13 01:01 UTC, SecondThread commented on src/armory/CreateNewTankPopup.js
> +export default CreateNewTankPopup;
Thanks, this file looks good

2020-03-13 01:01 UTC, SecondThread commented on src/armory/Armory.js
> +	//The || in the values are for a warning read more here https://github.com/mui-org/material-ui/issues/4904
We talked about it offline, but this is hiding a warning from us that we want to see if it happening. I can't reproduce it easily on my end, but we want to see these warnings when someone refactors this

2020-03-13 01:01 UTC, SecondThread commented on src/armory/Armory.js
> +							{tankOptions.map(({ value, label }, index) => <option key={index}  value={value}>{label}</option>)}
I know this isn't part of the changes you made here (so you don't have to fix it before pushing, just something to keep in mind): the way that this stuff is stored with the value/label/index is pretty confusing

2020-03-13 01:01 UTC, SecondThread commented on src/armory/Armory.js
> +							value={this.state.selectedChassis || ''}
Talked about offline, but make sure you delete this `|| ''` and all similar ones before pushing

2020-03-13 01:21 UTC, JorgeVidal29 commented on src/armory/Armory.js
> +	//The || in the values are for a warning read more here https://github.com/mui-org/material-ui/issues/4904
Yes to future refactors, there is an issue when you select a tank that doesn't have a selected component. index.js:1 Warning: `value` prop on `select` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.

2020-03-13 01:22 UTC, JorgeVidal29 commented on src/armory/CreateNewTankPopup.js
> +export default CreateNewTankPopup;
Thank you

2020-03-13 01:23 UTC, merged