verifyLogin now checks if a user is logged in
RickLeinecker/Fortuna pull request #193
Opened 2020-03-16 23:16 UTC by blaiadam

**Description**
verifyLogin will change all the Links on the pages to lead to login if a user is not logged in.

Resolves #122 
Resolves #145 

**Type of change**
Check options that are relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Fix or feature that would cause existing functionality to not work as expected
- [ ] This change requires a update in the design document

**Steps to Verify Functionality**
1. Go to website.
2. Type in the URL to go to MainMenu.
3. Click any link to any other page.
4. Should lead back to Login.

**Final Checklist:**
Go down the list and check them off.

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the design document (if applicable)
- [x] My changes generate no new warnings
- [x] Pulled updated master branch (if changed since branch creation) and corrected any conflicts, if any occur.

2020-03-17 00:24 UTC, SecondThread requested changes
If I am reading this correctly, this doesn't actually handle issue #145. You need to redirect to the login page when any page is loaded, not when any link is clicked. For example, someone might save bookmark on their browser, or click a link to fortunacombat.com/Armory. If you just typed that into the URL, it wouldn't redirect to the login, right?

The other thing you need to do, which probably requires talking to @Airor4 is verifying that the login token for that user is valid. The cookie might exist, but if you have logged in somewhere else, it wouldn't be accepted, so the webpage would still malfunction. 

We might also loose validity of a token when we have a page open but haven't refreshed it. This needs to be checked **every time we make an API call** so this might require extracting api calls into own files/helper functions.

IIRC, you can redirect to the login page just with something like this:
https://stackoverflow.com/questions/4744751/how-do-i-redirect-with-javascript

I am pretty sure we have some window.hrefs lying around in the code if you look for window.* you should be able to find some examples

2020-03-17 00:24 UTC, SecondThread commented on src/globalComponents/LinkType.js
> +type LinkType = 'Login' | 'MainMenu' | 'Marketplace' | 'Casus' | 'BattleArena' | 'Armory' | 'Battleground';
Thanks

2020-03-17 16:04 UTC, blaiadam commented
> IIRC, you can redirect to the login page just with something like this:
> https://stackoverflow.com/questions/4744751/how-do-i-redirect-with-javascript

I forgot you sent me some help, sorry should have reviewed this. I hope that my changes are sufficient.

2020-03-17 16:23 UTC, SecondThread commented on src/index.js
> +				<Route path="/MainMenu" component={(loggedIn) ? MainMenu : Login} />
If this works, that's really cool

2020-03-17 16:23 UTC, SecondThread commented on src/index.js
> +const loggedIn: boolean = (cookie.get('token')) ? true : false;
You also need to make sure the token is valid. If you log on with a second computer the token won't be valid, but it will exist.

2020-03-17 16:23 UTC, SecondThread commented on src/index.js
> +const loggedIn: boolean = (cookie.get('token')) ? true : false;
You and baylor have to implement some sort of verifyToken api call to do this

2020-03-26 00:43 UTC, Derplime approved these changes
Verified manual URL entries to the following location as a non-logged in user redirect to Login:
MainMenu 👍 
Armory 👍 
Marketplace 👍 
Casus 👍 
Training Arena 👍 
Battleground 👍
Battle Arena 👍

2020-03-26 01:19 UTC, SecondThread commented on src/battlearena/BattleArena.js
> +					linkName="/MainMenu"
should this be verifyLink(...)?

2020-03-26 01:19 UTC, SecondThread commented on src/casus/CasusContainer.js
> +					linkName='/Armory'
verifyLink?

2020-03-26 01:20 UTC, SecondThread commented on src/mainmenu/MainMenu.js
> +					linkName="/Login"
verifyLink

2020-03-26 01:20 UTC, SecondThread commented on src/marketplace/Marketplace.js
> +					linkName="/MainMenu"
ditto

2020-03-26 01:20 UTC, SecondThread commented on src/trainingarena/TrainingArena.js
> +					linkName="/BattleArena"
ditto

2020-03-26 01:20 UTC, SecondThread approved these changes
Mostly looks good and unsubstantial to me, just a few missing verifyLinks

2020-03-26 01:24 UTC, blaiadam commented on src/casus/CasusContainer.js
> +					linkName='/Armory'
The verifyLink is done inside navbar.

2020-03-26 01:24 UTC, merged