Jorge
RickLeinecker/Fortuna pull request #35
Opened 2019-12-22 21:20 UTC by JorgeVidal29

**Description**
Redesign of the login site and starter code to connect to database.
Passes flow and my testing

2019-12-23 04:43 UTC, SecondThread requested changes
Pretty much perfect, only requesting changes because we need to add package-lock.json to the .gitignore so we don't have these massive autogenerated changes.

As soon as you get rid of the package-lock changes, ping me and I'll stamp

2019-12-23 04:43 UTC, SecondThread commented on fortuna/src/LoginPopup.js
> +	    <div className="content">
Fix whitespace/indentation inconsistencies here please

2019-12-23 04:43 UTC, SecondThread commented on fortuna/src/login/Login.js
> +  |};
nit: make the closing |} indentation match the indentation level of type (like you would with a for loop or method).

Thanks for fixing this though :)

2019-12-23 04:43 UTC, SecondThread commented on fortuna/src/login/Login.js
> +  };
Same nit, but again, thanks for fixing :)

2019-12-27 03:09 UTC, SecondThread approved these changes

2019-12-27 03:10 UTC, JorgeVidal29 commented
> git fetch origin

2019-12-27 03:10 UTC, merged